sample_app/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get 'todolists/new'
  get 'top' => 'homes#top'
  post 'todolists' => 'todolists#create'
  get 'todolists' => 'todolists#index'

  get 'todolists/:id' => 'todolists#show',as:'todolist'
  get 'todolists/:id/edit' => 'todolists#edit',as:'edit_todolist'
  patch 'todolists/:id' => 'todolists#show',as:'update_todolist'
  delete 'tofolists/:id' => 'todolists#destory', as:'destory_todolist'
end
Refile.secret_key = 'dbf25742aea887cf6c770ca0b31d18bf605ab8c30f0da5d515730216d25999f327591f25873b759297d2768fcfd5edf772c90c8cf0c1896f6bd5c25bc7c9fb43'

sample_app/app/models/list.rb
class List < ApplicationRecord
    attachment :image
end

sample_app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

sample_app/app/controllers/homes_controller.rb
class HomesController < ApplicationController
    def top
    end

end

sample_app/app/controllers/todolists_controller.rb
class TodolistsController < ApplicationController
  def new
    @list = List.new
  end

 def create
    list = List.new(list_params)
    list.save
    redirect_to todolist_path(list.id)
 end
 def index
  @list = List.all
 end

 def show
  @list =List.find(params[:id])
 end
 def edit
  @list =List.find(params[:id])
 end
 def update
  list =List.find(parmes[:id])
  list.update(list_params)
  redirect_to todolist_path(list.id)
 end
 def destory
  list = List.find(params[:id])
  list.destroy
  redirect_to todolists_path
 end

 private

 def list_params
   params.require(:list).permit(:title,:body,:image)
 end

end

sample_app/app/helpers/homes_helper.rb
module HomesHelper
end

sample_app/app/helpers/todolist_helper.rb
module TodolistHelper
end

sample_app/app/views/homes/top.html.erb
<h1>ここはTopページです。</h1>

sample_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SampleApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

sample_app/app/views/todolists/edit.html.erb
<h1>編集画面</h1>
<%=form_for(@list,url:"/todolists/#{@list.id}") do |f| %>
 <h4>タイトル</h4>
 <%= f.text_field :title %>
 <h4>本文</h4>
 <%= f.text_area :body %>
 <%= f.submit '保存' %>
<% end %>

sample_app/app/views/todolists/index.html.erb
<h1>投稿一覧</h1>
<% @list.each do |list| %>
    <p>タイトル</p>
    <span>
    <%=link_to list.title, todolist_path(list.id) %>
    </span>
    <p>画像</p>
    <%= attachment_image_tag list, :image, :fill, 100, 100, format: 'jpeg' %>
<% end %>

sample_app/app/views/todolists/new.html.erb
<h1>新規投稿</h1>
<!-- form_for部分 -->
<%= form_for(@list, url: '/todolists') do |f| %>
 
    <h4>タイトル</h4>
    <%= f.text_field :title %>
 
    <h4>本文</h4>
    <%= f.text_area :body %>

    <h4>画像</h4>
    <%= f.attachment_field :image %>
 
    <%= f.submit '投稿' %>

  
 
<% end %>

sample_app/app/views/todolists/show.html.erb
<h2>タイトル</h2>
<p><%= @list.title %></p>
<h2>本文</h2>
<p><%= @list.body %></p>
<h2>画像</h2>
<%= attachment_image_tag @list, :image, format: 'jpeg',size:"100x100" %>

<%= link_to "編集", edit_todolist_path(@list.id) %>
<%= link_to "削除", destory_todolist_path(@list.id), method: :delete, "date-confirm" => "本当に削除しますか？" %>